### ISSUE TITLE
How add 2nd tag (invalid yaml)

### ISSUE THREAD

**Issue by McPaHa** [akx/hass-ruuvitag#25]
Hi!

Sorry to bother but what is correct procedure to add second ruuvitag? What I have to write to configuration page?

At the moment configuration is:

```yaml
interval: 30
debug: 0
tags:
  - id: c3c89c0e433b
    name: sauna
    enabled: true
    temperature: true
    pressure: true
    humidity: true
    battery: true
    acceleration: false
    accelerationX: false
    accelerationY: false
    accelerationZ: false
```

And log is telling me:

To have its status posted to Home Assistant, add the following to the tags configuration:
  {"id":"cdc31baa8a4b","name":"some-name","enabled":true,"temperature":true,"pressure":true,"humidity":true,"battery":true,"acceleration":false,"accelerationX":false,"accelerationY":false,"accelerationZ":false}

I've tried this multiple ways but it gives me YAML error every time... Any help?

**Comment by Zilenzioo** [comment]
```yaml
interval: 30
debug: 0
tags:
  - id: df4467928bb6
    name: Sensor1
    enabled: true
    temperature: true
    pressure: true
    humidity: true
    battery: true
    acceleration: false
    accelerationX: false
    accelerationY: false
    accelerationZ: false
  - id: c60b2a13487a
    name: Sensor2
    enabled: true
    temperature: true
    pressure: true
    humidity: true
    battery: true
    acceleration: false
    accelerationX: false
    accelerationY: false
    accelerationZ: false
  - id: f3a86a15d139
    name: Sensor3
    enabled: true
    temperature: true
    pressure: true
    humidity: true
    battery: true
    acceleration: false
    accelerationX: false
    accelerationY: false
    accelerationZ: false
```
